version: '3.8'

services:
  abc-helper:
    build: .
    image: abc-helper-local:latest
    container_name: abc-helper-app
    restart: always
    ports:
      - "8080:80"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./sounds:/usr/share/nginx/html/sounds